export const FETCH_USER = 'FETCH_USER';

export const ADD_SESSIONCASE = 'ADD_SESSIONCASE';

export const DELETE_SESSIONCASE = 'DELETE_SESSIONCASE';

export const SELECT_SESSIONCASE = 'SELECT_SESSIONCASE';

export const DESELECT_SESSIONCASE = 'DESELECT_SESSIONCASE';

export const SET_TIMEITTOOK = 'SET_TIMEITTOOK';

export const SET_SESSIONPAGE = 'SET_SESSIONPAGE';

export const SET_SESSIONTIME = 'SET_SESSIONTIME';

export const START_SESSION = 'START_SESSION';

export const RESUME_SESSION = 'RESUME_SESSION';

export const PAUSE_SESSION = 'PAUSE_SESSION';

export const END_SESSION = 'END_SESSION';

export const SET_RECAPCASE = 'SET_RECAPCASE';

export const SET_FIRSTSCOREAVERAGE = 'SET_FIRSTSCOREAVERAGE';

export const SET_FIRSTSCORE = 'SET_FIRSTSCORE';

export const SET_FIRSTTIME = 'SET_FIRSTTIME';

export const SET_CLOCKSTATE = 'SET_CLOCKSTATE';

export const SET_ADMINCASES = 'SET_ADMINCASES';

export const SET_SEARCHARRAY = 'SET_SEARCHARRAY';

export const SET_USERSEARCHARRAY = 'SET_SEARCHARRAY';
export const SET_USERCASES = 'SET_USERCASES';

export const SET_USERS = 'SET_USERS';

export const SET_SYSTEMEARRAY = 'SET_SYSTEMEARRAY';

export const SET_REASONARRAY = 'SET_REASONARRAY';

export const SET_NAMEARRAY = 'SET_NAMEARRAY';


    
